name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'ios/**'
      - 'README_zh.md'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'ios/**'
      - 'README_zh.md'
      - 'README.md'

env:
  NODE_VERSION: '18'

jobs:
  lint-and-test:
    name: Code Check and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run ESLint
        run: npm run lint

      - name: Run type check
        run: npm run typecheck

      - name: Build test
        run: npm run build
        env:
          MINIO_ENDPOINT: 'http://localhost'
          MINIO_PORT: '9000'
          MINIO_ROOT_USER: 'test'
          MINIO_ROOT_PASSWORD: 'test'
